#!/usr/bin/python3


def raise_exception():
    raise TypeError("there was an error")
